module ApplicationHelper
	# for state drop down menus
	def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end
  # helper method for select drop down of cities
  def sofl_cities
    [
    	['Atlantis', 'Atlantis' ],
			['Aventura', 'Aventura' ],
			['Bal Harbour', 'Bal Harbour' ],
			['Bay Harbor Islands', 'Bay Harbor Islands' ],
			['Belle Glade', 	'Belle Glade' ],
			['Biscayne Park', 'Biscayne Park' ],
			['Biscayne Gardens', 'Biscayne Gardens' ],
			['Boca Raton', 	'Boca Raton' ],
			['Briny Breezes', 'Briny Breezes' ],
			['Un-Incorporated Broward County', 'Un-Incorporated Broward County' ],
			['Canal Point', 'Canal Point' ],
			['Cloud Lake', 	'Cloud Lake' ],
			['Cocnut Creek', 'Cocnut Creek' ],
			['Cocnut Grove', 'Cocnut Grove' ],
			['Cooper City', 'Cooper City' ],
			['Coral Gables', 'Coral Gables' ],
			['Coral Springs', 'Coral Springs' ],
			['Crandon Park', 'Crandon Park' ],
			['Cutler Bay', 'Cutler Bay' ],
			['Unincorporated Dade County', 'Unincorporated Dade County' ],
			['Dania ', 'Dania ' ],
			['Davie', 'Davie' ],
			['Deerfield Beach', 'Deerfield Beach' ],
			['Delray Beach ', 'Delray Beach ' ],
			['Doral', 'Doral' ],
			['Eastern Shores', 'Eastern Shores' ],
			['El Portal', 'El Portal' ],
			['Fellsmere', 'Fellsmere' ],
			['Fisher Island', 'Fisher Island' ],
			['Florida City', 'Florida City' ],
			['Fort Lauderdale', 'Fort Lauderdale' ],
			['Fort Pierce', 	'Fort Pierce' ],
			['Glen Ridge', 'Glen Ridge' ],
			['Golden Beach', 'Golden Beach' ],
			['Goulds', 'Goulds' ],
			['Green Acres', 'Green Acres' ],
			['Gulfstream', 'Gulfstream' ],
			['Gulfview', 'Gulfview' ],
			['Hallandale', 'Hallandale' ],
			['Haverhill', 'Haverhill' ],
			['Hialeah', 'Hialeah' ],
			['Hiahleah Gardens', 'Hiahleah Gardens' ],
			['Highland Beach', 'Highland Beach' ],
			['Hillsboro Beach',  'Hillsboro Beach' ],
			['Hobo Sound',  'Hobo Sound' ],
			['Hollywood',  'Hollywood' ],
			['Homestead',  'Homestead' ],
			['Hutchinson Island', 'Hutchinson Island' ],
			['Hypoluxo', 'Hypoluxo' ],
			['Indian Creek', 'Indian Creek' ],
			['Indian River Shores', 	'Indian River Shores' ],
			['Indian Town', 	'Indian Town' ],
			['Islands/Caribbean', 'Islands/Caribbean' ],
			['Jenson Beach', 'Jenson Beach' ],
			['Juno Beach', 'Juno Beach' ],
			['Jupiter Inlet Colony', 'Jupiter Inlet Colony' ],
			['Jupiter', 'Jupiter' ],
			['Kendall', 'Kendall' ],
			['Key Biscayne', 'Key Biscayne' ],
			['Lake Clarke Shores', 'Lake Clarke Shores' ],
			['Lake Park', 'Lake Park' ],
			['Lake Worth', 	'Lake Worth' ],
			['Lakewood Park',  'Lakewood Park' ],
			['Lantana', 	'Lantana' ],
			['Lauderdale By The Sea', 	'Lauderdale By The Sea' ],
			['Lauderhill', 	'Lauderhill' ],
			['Lauderdale Lakes', 	'Lauderdale Lakes' ],
			['Lazy Lake', 	'Lazy Lake' ],
			['Lighthouse Point', 	'Lighthouse Point' ],
			['Loxahatchee', 	'Loxahatchee' ],
			['Manalapan',  'Manalapan' ],
			['Mangonia Park',  'Mangonia Park' ],
			['Margate', 	'Margate' ],
			['Medley', 	'Medley' ],
			['Miami', 	'Miami' ],
			['Miami Beach', 	'Miami Beach' ],
			['Miami Gardens', 	'Miami Gardens' ],
			['Miami Lakes', 	'Miami Lakes' ],
			['Miami Shores', 	'Miami Shores' ],
			['Miami Springs', 	'Miami Springs' ],
			['Miramar', 	'Miramar' ],
			['Naranja', 	'Naranja' ],
			['North Bay Village', 	'North Bay Village' ],
			['North Lauderdale', 	'North Lauderdale' ],
			['North Miami', 	'North Miami' ],
			['North Miami Beach', 	'North Miami Beach' ],
			['North Palm Beach', 	'North Palm Beach' ],
			['Oakland Park ', 	'Oakland Park ' ],
			['Ocean Ridge', 	'Ocean Ridge' ],
			['Opa-Locka', 	'Opa-Locka' ],
			['Other City Value  - Out of Area', 	'Other City Value  - Out of Area' ],
			['Other County - Not In USA', 	'Other County - Not In USA' ],
			['Other City - In the State of Florida', 	'Other City - In the State of Florida' ],
			['Other City - Keys/Islands/Caribbean', 	'Other City - Keys/Islands/Caribbean' ],
			['Other City - Not in the State of Florida', 	'Other City - Not in the State of Florida' ],
			['Pahokee', 	'Pahokee' ],
			['Palm Beach', 	'Palm Beach' ],
			['Un-Incoporated PB County ', 	'Un-Incoporated PB County ' ],
			['Palmetto Bay', 	'Palmetto Bay' ],
			['Palm Springs', 	'Palm Springs' ],
			['Parkland', 	'Parkland' ],
			['Palm Beach Gardens', 	'Palm Beach Gardens' ],
			['Palm Beach Shores', 	'Palm Beach Shores' ],
			['Pembroke Park', 	'Pembroke Park' ],
			['Pembroke Pines', 	'Pembroke Pines' ],
			['Pennsuco', 	'Pennsuco' ],
			['Perrine', 	'Perrine' ],
			['Pinecrest', 	'Pinecrest' ],
			['Plantation', 	'Plantation' ],
			['Pompano Beach', 	'Pompano Beach' ],
			['Port Salerno', 	'Port Salerno' ],
			['Port St. Lucie', 	'Port St. Lucie' ],
			['Riviera Beach', 	'Riviera Beach' ],
			['Roseland', 	'Roseland' ],
			['Royal Palm Beach', 	'Royal Palm Beach' ],
			['Sea Ranch Lakes', 	'Sea Ranch Lakes' ],
			['Sebastian', 	'Sebastian' ],
			['Sewalls Point', 	'Sewalls Point' ],
			['Singer Island', 	'Singer Island' ],
			['South Miami', 	'South Miami' ],
			['South Bay', 	'South Bay' ],
			['South Palm Beach', 	'South Palm Beach' ],
			['Saint Lucie West ', 	'Saint Lucie West ' ],
			['Stuart', 	'Stuart' ],
			['Sunny Isles Beach', 	'Sunny Isles Beach' ],
			['Sunrise', 	'Sunrise' ],
			['Surfside', 	'Surfside' ],
			['Sweetwater', 	'Sweetwater' ],
			['Southwest Ranches', 	'Southwest Ranches' ],
			['Tamarac', 	'Tamarac' ],
			['Tequesta', 	'Tequesta' ],
			['Tropic', 	'Tropic' ],
			['Vergo Beach', 	'Vergo Beach' ],
			['Virginia Key', 	'Virginia Key' ],
			['Virginia Gardbes', 	'Virginia Gardbes' ],
			['Village of Golf', 	'Village of Golf' ],
			['Wabasso', 	'Wabasso' ],
			['Wellington', 	'Wellington' ],
			['Weston', 	'Weston' ],
			['Wilton Manors', 	'Wilton Manors' ],
			['West Miami', 	'West Miami' ],
			['Williams Island', 	'Williams Island' ],
			['Winter Beach', 	'Winter Beach' ],
			['West Palm Beach', 	'West Palm Beach' ],
			['West Park ', 	'West Park ' ]
  	]
  end

  #helper method for select drop down of counties
  def sofl_counties
  	[
  		['Broward County', 'Broward County'],
  		['Miami-Dade County', 'Miami-Dade County'],
  		['West Palm Beach County', 'West Palm Beach County'],
  		['Other County', 'Other County']
    ]
  end

  # helper method for select drop down of compass directions
  def compass_directions
  	[
  		['N','N'],
  		['NE', 'NE'],
  		['E', 'E'],
  		['SE', 'SE'],
  		['S', 'S'],
  		['SW', 'SW'],
  		['W', 'W'],
  		['NW', 'NW'],
  	]
  end
end
