module BuildingsHelper
	def sofl_elem
		[
			['Air Base',	'Air Base'],
			['Allapattah',	'Allapattah'],
			['Maya Angelou',	'Maya Angelou'],
			['Arch Creek',	'Arch Creek'],
			['Arcola Lake',	'Arcola Lake'],
			['Ashe; Bowman F.',	'Ashe; Bowman F.'],
			['Atlantic West',	'Atlantic West'],
			['Auburndale',	'Auburndale'],
			['Avocado',	'Avocado'],
			['Banyan ',	'Banyan '],
			['Dr. Manuel C Barreiro',	'Dr. Manuel C Barreiro'],
			['Bay Harbor',	'Bay Harbor'],
			['Bayview',	'Bayview'],
			['Beckham; Ethel Koger',	'Beckham; Ethel Koger'],
			['Bel-Aire',	'Bel-Aire'],
			['Bennett',	'Bennett'],
			['Bent Tree',	'Bent Tree'],
			['Bethune; Mary M.',	'Bethune; Mary M.'],
			['Biscayne',	'Biscayne'],
			['Biscayne Gardens',	'Biscayne Gardens'],
			['Blanton; Van E.',	'Blanton; Van E.'],
			['Blue Lakes',	'Blue Lakes'],
			['Boulevard Hgts',	'Boulevard Hgts'],
			['Norma Butler Bossard',	'Norma Butler Bossard'],
			['Brentwood',	'Brentwood'],
			['Bright; James H.',	'Bright; James H.'],
			['Broadmoor',	'Broadmoor'],
			['Broadview',	'Broadview'],
			['Broward Estates',	'Broward Estates'],
			['Buena Vista',	'Buena Vista'],
			['Bunche Park',	'Bunche Park'],
			['Calusa',	'Calusa'],
			['Campbell Drive',	'Campbell Drive'],
			['Caribbean',	'Caribbean'],
			['Carol City',	'Carol City'],
			['Carver; G.W.',	'Carver; G.W.'],
			['Castle Hill Anx',	'Castle Hill Anx'],
			['Castle Hill ',	'Castle Hill '],
			['Challenger',	'Challenger'],
			['Chapman; W.',	'Chapman; W.'],
			['Chapel Trail',	'Chapel Trail'],
			['Citrus Grove',	'Citrus Grove'],
			['Christina M Eve',	'Christina M Eve'],
			['Central Park ',	'Central Park '],
			['Country Hills',	'Country Hills'],
			['Country Isles',	'Country Isles'],
			['Coconut Grove',	'Coconut Grove'],
			['Coconut Crk Elem',	'Coconut Crk Elem'],
			['Coconut Palm ',	'Coconut Palm '],
			['Colbert',	'Colbert'],
			['Collins',	'Collins'],
			['Colonial Drive',	'Colonial Drive'],
			['Comstock',	'Comstock'],
			['Cooper City',	'Cooper City'],
			['Coral Grove',	'Coral Grove'],
			['Coral Springs',	'Coral Springs'],
			['Coral Park',	'Coral Park'],
			['Coral Reef',	'Coral Reef'],
			['Coral Terrace',	'Coral Terrace'],
			['Coral Way',	'Coral Way'],
			['Cresthaven',	'Cresthaven'],
			['Crestview',	'Crestview'],
			['Croissant Park',	'Croissant Park'],
			['Crowder; Thena',	'Crowder; Thena'],
			['Cutler Ridge',	'Cutler Ridge'],
			['Cypress ',	'Cypress '],
			['Dania',	'Dania'],
			['Dante Fascell',	'Dante Fascell'],
			['Davie',	'Davie'],
			['Devon-Aire',	'Devon-Aire'],
			['Dillard Elem',	'Dillard Elem'],
			['Discovery',	'Discovery'],
			['Dolphin Bay',	'Dolphin Bay'],
			['Douglas',	'Douglas'],
			['Drew; Charles',	'Drew; Charles'],
			['Drew; Charles R.',	'Drew; Charles R.'],
			['Deerfield Beach',	'Deerfield Beach'],
			['Deerfield Park',	'Deerfield Park'],
			['Driftwood',	'Driftwood'],
			['Dunbar',	'Dunbar'],
			['Dipuis; J.G.',	'Dipuis; J.G.'],
			['Eagle Point',	'Eagle Point'],
			['Eagle Ridge',	'Eagle Ridge'],
			['Earhart; Amelia',	'Earhart; Amelia'],
			['Earlington Heights',	'Earlington Heights'],
			['Edison Park ',	'Edison Park '],
			['Embassy Creek ',	'Embassy Creek '],
			['Emerson',	'Emerson'],
			['Endeavor Prim Learning Cntr',	'Endeavor Prim Learning Cntr'],
			['Evans; Lillie C.',	'Evans; Lillie C.'],
			['Everglades',	'Everglades'],
			['Edward Whigham',	'Edward Whigham'],
			['Farichild; David',	'Farichild; David'],
			['Fairlawn',	'Fairlawn'],
			['Fairway',	'Fairway'],
			['Douglass; Frederick',	'Douglass; Frederick'],
			['Feinberg; Leroy D.',	'Feinberg; Leroy D.'],
			['Finlay Dr. Calos',	'Finlay Dr. Calos'],
			['Flagami',	'Flagami'],
			['Flagler, Henry M.',	'Flagler, Henry M.'],
			['Flamingo',	'Flamingo'],
			['Floranada',	'Floranada'],
			['Florida City',	'Florida City'],
			['Floral Heights',	'Floral Heights'],
			['Floyd; Gloria',	'Floyd; Gloria'],
			['Forest Hills',	'Forest Hills'],
			['Foster; Stephen',	'Foster; Stephen'],
			['Fox Trail',	'Fox Trail'],
			['Franklin; Benjamin',	'Franklin; Benjamin'],
			['Fulford',	'Fulford'],
			['Coral Gables',	'Coral Gables'],
			['Gator Run',	'Gator Run'],
			['Golden Glades',	'Golden Glades'],
			['Good; Joella',	'Good; Joella'],
			['Goulds',	'Goulds'],
			['Graham',	'Graham'],
			['Gratigny',	'Gratigny'],
			['Greenglade',	'Greenglade'],
			['Greynolds Park',	'Greynolds Park'],
			['Griffin',	'Griffin'],
			['Gulfstream',	'Gulfstream'],
			['Hardley; Charles R.',	'Hardley; Charles R.'],
			['Hall; Joe',	'Hall; Joe'],
			['Hallandale Elem',	'Hallandale Elem'],
			['Hartner; Eneida',	'Hartner; Eneida'],
			['Hawkes Bluff',	'Hawkes Bluff'],
			['Heron Heights',	'Heron Heights'],
			['Hialeah Gardens',	'Hialeah Gardens'],
			['Hialeah',	'Hialeah'],
			['Hibiscus',	'Hibiscus'],
			['Highland Oaks',	'Highland Oaks'],
			['Holmes',	'Holmes'],
			['Hoover; Oliver',	'Hoover; Oliver'],
			['Horizon',	'Horizon'],
			['Howard Drive',	'Howard Drive'],
			['Hunt; James S.',	'Hunt; James S.'],
			['Hollywood Centl',	'Hollywood Centl'],
			['Hollywood HI Elem',	'Hollywood HI Elem'],
			['Hollywood Park ',	'Hollywood Park '],
			['Indian Trace',	'Indian Trace'],
			['Dr Robert B Ingram',	'Dr Robert B Ingram'],
			['Ives; Madie',	'Ives; Madie'],
			['Jack Gordon',	'Jack Gordon'],
			['Johnson; J.W',	'Johnson; J.W'],
			['Kendale',	'Kendale'],
			['Kendale Lakes',	'Kendale Lakes'],
			['Kensington Park',	'Kensington Park'],
			['Kenwood',	'Kenwood'],
			['Keybiscayne',	'Keybiscayne'],
			['Kinlock Park',	'Kinlock Park'],
			['Lake Forest',	'Lake Forest'],
			['Lakeside',	'Lakeside'],
			['Larkdale',	'Larkdale'],
			['Lauderhill Elem',	'Lauderhill Elem'],
			['Lauderdale Mnrs',	'Lauderdale Mnrs'],
			['Lauderhill; Paul Turner',	'Lauderhill; Paul Turner'],
			['Leewood',	'Leewood'],
			['Lehman; William H.',	'Lehman; William H.'],
			['Leisure City',	'Leisure City'],
			['Lenti; Linda',	'Lenti; Linda'],
			['Lewis; A.L.',	'Lewis; A.L.'],
			['Liberty City',	'Liberty City'],
			['Liberty',	'Liberty'],
			['Little River',	'Little River'],
			['Lake Stevens',	'Lake Stevens'],
			['Lakeview',	'Lakeview'],
			['Lloyd Estates',	'Lloyd Estates'],
			['Lorah Park',	'Lorah Park'],
			['Louverture; Toussaint',	'Louverture; Toussaint'],
			['Ludlam',	'Ludlam'],
			['Manatee Bay',	'Manatee Bay'],
			['Maple Wood',	'Maple Wood'],
			['Margate Elem',	'Margate Elem'],
			['Markham; Robert',	'Markham; Robert'],
			['Marshall; Thurgd',	'Marshall; Thurgd'],
			['Martin Lut King',	'Martin Lut King'],
			['Mattews; Wesley',	'Mattews; Wesley'],
			['Jesse J McCrary Jr. ',	'Jesse J McCrary Jr. '],
			['Mcnab',	'Mcnab'],
			['Meadowlane',	'Meadowlane'],
			['Meadowbrook',	'Meadowbrook'],
			['Melrose',	'Melrose'],
			['Merritt; Ada',	'Merritt; Ada'],
			['Miami Gardens',	'Miami Gardens'],
			['Miami Heights',	'Miami Heights'],
			['Miami Lakes',	'Miami Lakes'],
			['Miami Park',	'Miami Park'],
			['Miami Shores',	'Miami Shores'],
			['Miami Springs',	'Miami Springs'],
			['Milam; MA',	'Milam; MA'],
			['Miller; Phyllis R',	'Miller; Phyllis R'],
			['Miramar Elem',	'Miramar Elem'],
			['Mirror Lakes',	'Mirror Lakes'],
			['Kind; Martin L. ',	'Kind; Martin L. '],
			['Morningside',	'Morningside'],
			['Morrow',	'Morrow'],
			['Moton; R.R',	'Moton; R.R'],
			['Myrtle Grove',	'Myrtle Grove'],
			['N Andrews Gardens',	'N Andrews Gardens'],
			['Naranja',	'Naranja'],
			['Natural Bridge',	'Natural Bridge'],
			['North Beach ',	'North Beach '],
			['North Carol City',	'North Carol City'],
			['North County',	'North County'],
			['No. Dade Ctr./Modern Lang.',	'No. Dade Ctr./Modern Lang.'],
			['North Fork ',	'North Fork '],
			['North Glade',	'North Glade'],
			['North Hialeah',	'North Hialeah'],
			['N Lauderdale',	'N Lauderdale'],
			['North Miami',	'North Miami'],
			['Nob Hill',	'Nob Hill'],
			['Norcrest',	'Norcrest'],
			['Norland',	'Norland'],
			['Norwood',	'Norwood'],
			['Nova B. Forman',	'Nova B. Forman'],
			['Nova Eisenhower',	'Nova Eisenhower'],
			['North Side',	'North Side'],
			['North Twin Lakes',	'North Twin Lakes'],
			['Oak Grove',	'Oak Grove'],
			['Oakland Park',	'Oakland Park'],
			['Oakridge',	'Oakridge'],
			['Okust',	'Okust'],
			['Olinda',	'Olinda'],
			['Olympia Heights',	'Olympia Heights'],
			['Opa Locka',	'Opa Locka'],
			['Orchard Villa',	'Orchard Villa'],
			['Oriole',	'Oriole'],
			['Palmetto',	'Palmetto'],
			['Palm Glades ',	'Palm Glades '],
			['Palmview',	'Palmview'],
			['Panther Run',	'Panther Run'],
			['Park Ridge',	'Park Ridge'],
			['Parkside',	'Parkside'],
			['Park Springs',	'Park Springs'],
			['Park Trails',	'Park Trails'],
			['Parkview',	'Parkview'],
			['Parkway',	'Parkway'],
			['Pasadena Lakes',	'Pasadena Lakes'],
			['Pembroke Pines',	'Pembroke Pines'],
			['Pembroke Lakes',	'Pembroke Lakes'],
			['Pepper; Claude',	'Pepper; Claude'],
			['Perrine',	'Perrine'],
			['Perry; Annabel',	'Perry; Annabel'],
			['Pesko',	'Pesko'],
			['Peters',	'Peters'],
			['Pharr; Kelsey L.',	'Pharr; Kelsey L.'],
			['Pinecrest',	'Pinecrest'],
			['Pine Lake',	'Pine Lake'],
			['Pine Villa',	'Pine Villa'],
			['Pinewood',	'Pinewood'],
			['Park Lakes',	'Park Lakes'],
			['Plantation',	'Plantation'],
			['Palm Lakes',	'Palm Lakes'],
			['Palm Springs',	'Palm Springs'],
			['Palm Springs North',	'Palm Springs North'],
			['Plantation Park',	'Plantation Park'],
			['Poinciana Parl',	'Poinciana Parl'],
			['Pompano Beach Elem',	'Pompano Beach Elem'],
			['Porter; Gilbert',	'Porter; Gilbert'],
			['Quiet Waters',	'Quiet Waters'],
			['Rainbow Park ',	'Rainbow Park '],
			['Redland',	'Redland'],
			['Reeves; Henry',	'Reeves; Henry'],
			['Richmond',	'Richmond'],
			['Riverglades',	'Riverglades'],
			['Riverland',	'Riverland'],
			['Riverside',	'Riverside'],
			['Ramblewood Elem',	'Ramblewood Elem'],
			['Robers; Jane S.',	'Robers; Jane S.'],
			['Rock Island',	'Rock Island'],
			['Rockway',	'Rockway'],
			['Royal Palm',	'Royal Palm'],
			['Royal Green',	'Royal Green'],
			['Sandpiper',	'Sandpiper'],
			['Santa Clara',	'Santa Clara'],
			['Saunders; Laura',	'Saunders; Laura'],
			['Sawgrass',	'Sawgrass'],
			['Scott Lake ',	'Scott Lake '],
			['Sea Castle',	'Sea Castle'],
			['Seminole',	'Seminole'],
			['Shadowlawn',	'Shadowlawn'],
			['Shenandoah',	'Shenandoah'],
			['Sheppard; Ben',	'Sheppard; Ben'],
			['Sheppard; Ben (Annex)',	'Sheppard; Ben (Annex)'],
			['Sheppard; Ben (Relief lI)',	'Sheppard; Ben (Relief lI)'],
			['Sheridan Hills',	'Sheridan Hills'],
			['Sheridan Park',	'Sheridan Park'],
			['Sibley Hubert',	'Sibley Hubert'],
			['Silver Bluff',	'Silver Bluff'],
			['Skyway',	'Skyway'],
			['Silver Lakes Elem',	'Silver Lakes Elem'],
			['Silver Palms',	'Silver Palms'],
			['Silver Ridge',	'Silver Ridge'],
			['Silver Shores',	'Silver Shores'],
			['South Miami Heights',	'South Miami Heights'],
			['South Miami',	'South Miami'],
			['Smith John I',	'Smith John I'],
			['Snapper Creek ',	'Snapper Creek '],
			['Saunders Park ',	'Saunders Park '],
			['South Hialeah',	'South Hialeah'],
			['Southside',	'Southside'],
			['Spanish Lakes',	'Spanish Lakes'],
			['South Pointe',	'South Pointe'],
			['Springsview',	'Springsview'],
			['Stirling',	'Stirling'],
			['Stirrup ',	'Stirrup '],
			['Sunset Lakes',	'Sunset Lakes'],
			['Sunland Park',	'Sunland Park'],
			['Sunset Park ',	'Sunset Park '],
			['Sunset',	'Sunset'],
			['Sunshine',	'Sunshine'],
			['Sweetwater',	'Sweetwater'],
			['Sylvania Heights',	'Sylvania Heights'],
			['Tamarac',	'Tamarac'],
			['Tedder',	'Tedder'],
			['Thomas; Eugenia',	'Thomas; Eugenia'],
			['Tradewinds',	'Tradewinds'],
			['Treasure Island',	'Treasure Island'],
			['Tropical ',	'Tropical '],
			['Tucker; F.S.',	'Tucker; F.S.'],
			['Twin Lakes',	'Twin Lakes'],
			['Village',	'Village'],
			['Village Green ',	'Village Green '],
			['Vineland',	'Vineland'],
			['Walker',	'Walker'],
			['Walters; Mae',	'Walters; Mae'],
			['Watkins',	'Watkins'],
			['Bryan; Williams J.',	'Bryan; Williams J.'],
			['Westchester',	'Westchester'],
			['Welleby',	'Welleby'],
			['West Little River',	'West Little River'],
			['Westview ',	'Westview '],
			['Westwood Hgts',	'Westwood Hgts'],
			['Wheatly; Phyllis',	'Wheatly; Phyllis'],
			['West Hialeah Gardens',	'West Hialeah Gardens'],
			['Whispering Pines',	'Whispering Pines'],
			['West Hollywodd',	'West Hollywodd'],
			['West Homestead',	'West Homestead'],
			['Wilton Manors',	'Wilton Manors'],
			['Winston Park ',	'Winston Park '],
			['West Laboratory',	'West Laboratory'],
			['Wychem Charles',	'Wychem Charles'],
			['Youngl Nathan',	'Youngl Nathan'],
			['Young; Virginia ',	'Young; Virginia '],
			['Zora Hurston ',	'Zora Hurston ']
					]
	end

	def sofl_middle
		[
		  ['Allapattah',	'Allapattah'],
			['Ammons; Herbert',	'Ammons; Herbert'],
			['Andover Middle',	'Andover Middle'],
			['Arvida',	'Arvida'],
			['Arthur Ashe Jr',	'Arthur Ashe Jr'],
			['Attucks',	'Attucks'],
			['Bair',	'Bair'],
			['Brownsville',	'Brownsville'],
			['Washington; B.T.',	'Washington; B.T.'],
			['Campbell Drive',	'Campbell Drive'],
			['Jorge Mass Canosa',	'Jorge Mass Canosa'],
			['Carol City',	'Carol City'],
			['Carver; G.W',	'Carver; G.W'],
			['Centennial',	'Centennial'],
			['Chiles; Lawton',	'Chiles; Lawton'],
			['Citrus Grove',	'Citrus Grove'],
			['Coral Spg Middle',	'Coral Spg Middle'],
			['Country Club',	'Country Club'],
			['Crystal Lakes',	'Crystal Lakes'],
			['Curry, Lamar Louise',	'Curry, Lamar Louise'],
			['Cutler Ridge',	'Cutler Ridge'],
			['Dandy; William',	'Dandy; William'],
			['Dario; Ruban',	'Dario; Ruban'],
			['de Dieg0; Jose',	'de Dieg0; Jose'],
			['Doral',	'Doral'],
			['Drew; Charles R.',	'Drew; Charles R.'],
			['Deerfield Beach',	'Deerfield Beach'],
			['Driftwood',	'Driftwood'],
			['Miami Edison',	'Miami Edison'],
			['Falcon Cove',	'Falcon Cove'],
			['Filer; Henry',	'Filer; Henry'],
			['Forest Glen',	'Forest Glen'],
			['Glades',	'Glades'],
			['Zelda Glazer',	'Zelda Glazer'],
			['Gulfstream',	'Gulfstream'],
			['Hammocks',	'Hammocks'],
			['Hialeah Gardens',	'Hialeah Gardens'],
			['Hialeah',	'Hialeah'],
			['HIghland Oaks',	'HIghland Oaks'],
			['Homestead',	'Homestead'],
			['Howard Doolin',	'Howard Doolin'],
			['Indian Ridge',	'Indian Ridge'],
			['Jefferson; Thomas',	'Jefferson; Thomas'],
			['Kennedy; J.F.',	'Kennedy; J.F.'],
			['Kinlock Park',	'Kinlock Park'],
			['Lauderhill Middle',	'Lauderhill Middle'],
			['Lauderdale Lks',	'Lauderdale Lks'],
			['Lake Stevens',	'Lake Stevens'],
			['Lyons Creek ',	'Lyons Creek '],
			['Madison',	'Madison'],
			['Mann; Horace',	'Mann; Horace'],
			['Margate Middle',	'Margate Middle'],
			['Marti; Jose',	'Marti; Jose'],
			['Mays',	'Mays'],
			['McMillan; H.D.',	'McMillan; H.D.'],
			['Mcnicol',	'Mcnicol'],
			['Miami Lakes',	'Miami Lakes'],
			['Miami Springs',	'Miami Springs'],
			['Millenium',	'Millenium'],
			['Nautilus',	'Nautilus'],
			['North Dade',	'North Dade'],
			['New Renaissance',	'New Renaissance'],
			['New River',	'New River'],
			['North Miami',	'North Miami'],
			['Norland',	'Norland'],
			['Nova Center',	'Nova Center'],
			['Olsen',	'Olsen'],
			['Palmetto',	'Palmetto'],
			['Parkway Middle',	'Parkway Middle'],
			['Paul Bell',	'Paul Bell'],
			['Perry; Henry D.',	'Perry; Henry D.'],
			['Pines',	'Pines'],
			['Pioneer',	'Pioneer'],
			['Plantation Middle',	'Plantation Middle'],
			['Palm Springs',	'Palm Springs'],
			['Pompano B. Middle',	'Pompano B. Middle'],
			['Pounce De Leon',	'Pounce De Leon'],
			['Redland',	'Redland'],
			['Richmond Heights',	'Richmond Heights'],
			['Rickards ',	'Rickards '],
			['Riviera',	'Riviera'],
			['Ramblewood Middle',	'Ramblewood Middle'],
			['Rockway',	'Rockway'],
			['Sawgrass Spgs ',	'Sawgrass Spgs '],
			['Seminole',	'Seminole'],
			['Shenandoah',	'Shenandoah'],
			['Silver Lakes Middle',	'Silver Lakes Middle'],
			['Silver Trail',	'Silver Trail'],
			['South Miami',	'South Miami'],
			['Southwood',	'Southwood'],
			['Sunrise',	'Sunrise'],
			['Tequesta Trace',	'Tequesta Trace'],
			['Thomas; WR',	'Thomas; WR'],
			['Westglades',	'Westglades'],
			['Westpine',	'Westpine'],
			['Westview',	'Westview'],
			['West Miami',	'West Miami'],
			['Young; Walter C',	'Young; Walter C'],  	
		]
	end

	def sofl_hs
		[
			['American',	'American'],
			['Anderson; Boyd',	'Anderson; Boyd'],
			['Atlantic Technical',	'Atlantic Technical'],
			['Miami Beach',	'Miami Beach'],
			['Braddock G. Holmes',	'Braddock G. Holmes'],
			['College Academy',	'College Academy'],
			['Miami Carol City',	'Miami Carol City'],
			['Miami Central',	'Miami Central'],
			['Coconut Crk High',	'Coconut Crk High'],
			['Coral Glades High',	'Coral Glades High'],
			['Cooper City',	'Cooper City'],
			['Coral Springs',	'Coral Springs'],
			['Miami Coral Park',	'Miami Coral Park'],
			['Corla Reef',	'Corla Reef'],
			['Cypress Bay',	'Cypress Bay'],
			['Design &Architecture',	'Design &Architecture'],
			['Dillard High',	'Dillard High'],
			['Deerfield Beach',	'Deerfield Beach'],
			['Miami Edison',	'Miami Edison'],
			['Ely',	'Ely'],
			['Everglades',	'Everglades'],
			['Flanagan; Charls',	'Flanagan; Charls'],
			['Ferguson John ',	'Ferguson John '],
			['Fort Lauderdale',	'Fort Lauderdale'],
			['Felix Valera',	'Felix Valera'],
			['Coral Gables',	'Coral Gables'],
			['Goleman Barbara',	'Goleman Barbara'],
			['Hallandale High',	'Hallandale High'],
			['Hialeah Gardens High ',	'Hialeah Gardens High '],
			['Hialeah ',	'Hialeah '],
			['Homestead',	'Homestead'],
			['Hollywood HI High',	'Hollywood HI High'],
			['Miami Jackson',	'Miami Jackson'],
			['Miami Killian',	'Miami Killian'],
			['Micheal Krop',	'Micheal Krop'],
			['Mast Academy',	'Mast Academy'],
			['McArthur',	'McArthur'],
			['McFatter Technical ',	'McFatter Technical '],
			['Miami Beach',	'Miami Beach'],
			['Miami Lakes Edu Cntr',	'Miami Lakes Edu Cntr'],
			['Hialeah-Miami Lakes',	'Hialeah-Miami Lakes'],
			['Miami Senior',	'Miami Senior'],
			['Miramar High',	'Miramar High'],
			['Monarch',	'Monarch'],
			['Robert Morgan Edu Ctr',	'Robert Morgan Edu Ctr'],
			['Alonzo and Tracy Mourning Sr High',	'Alonzo and Tracy Mourning Sr High'],
			['Northeast',	'Northeast'],
			['New World School of Art',	'New World School of Art'],
			['North Miami Beach',	'North Miami Beach'],
			['North Miami ',	'North Miami '],
			['Miami Norland',	'Miami Norland'],
			['Miami Northwestern',	'Miami Northwestern'],
			['Nova',	'Nova'],
			['Miami Palmetto ',	'Miami Palmetto '],
			['Piper',	'Piper'],
			['Plantation High',	'Plantation High'],
			['Pompano Institute',	'Pompano Institute'],
			['Ronald W. Reagan',	'Ronald W. Reagan'],
			['School for Advanced Studies Homestead',	'School for Advanced Studies Homestead'],
			['School for Advanced Studies North',	'School for Advanced Studies North'],
			['School for Advanced Studies South',	'School for Advanced Studies South'],
			['School for Advanced Studies Wolfson',	'School for Advanced Studies Wolfson'],
			['South Broward',	'South Broward'],
			['South Miami',	'South Miami'],
			['South Dade',	'South Dade'],
			['Miami Southridge',	'Miami Southridge'],
			['S Plantation',	'S Plantation'],
			['Miami Springs',	'Miami Springs'],
			['Stoneman; Douglas',	'Stoneman; Douglas'],
			['Stranahan',	'Stranahan'],
			['Miami Sunset ',	'Miami Sunset '],
			['Southwest Miami',	'Southwest Miami'],
			['Travella',	'Travella'],
			['Turner; WM Technical',	'Turner; WM Technical'],
			['Washington; Brooker T',	'Washington; Brooker T'],
			['West Broward',	'West Broward'],
			['Western',	'Western'],
			['West Land',	'West Land'],
			['Yound Mans Prep Academy',	'Yound Mans Prep Academy'],
			['Yound Womans Prep Academy',	'Yound Womans Prep Academy']
		]
	end
end
